version: '2'
services:
  acmefees-app:
    image: acmefees
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://acmefees-mongodb:27018
      - SPRING_DATA_MONGODB_DATABASE=AcmeFees
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  acmefees-mongodb:
    extends:
      file: docker-compose.yml
      service: acmefees-mongodb
